/*
Package include imports all prospector packages so that they register
their factories with the global registry. This package can be imported in the
main package to automatically register all of the standard supported prospectors
modules.
*/
package include

import (
	// This list is automatically generated by `make imports`
	_ "filebeat/prospector/log"
	_ "filebeat/prospector/redis"
	_ "filebeat/prospector/stdin"
	_ "filebeat/prospector/udp"
)
